# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c64b0976fe7ed557e91259654a6995898978e084f0bc26a6822f1864c81bf1af3c5971d02a0eb0240854d86a72a2b68abd9a5ba1eff10f0fe1b6f9a3754d0aa9

test:
  secret_key_base: 1f164bcfc6907b9ae96075143532abc78b24e3c791025fb9d88ef7315f4fd81b1339fdfbf9478ba3355b6c8b10d6f17823373438f1c46fecf7087bc98addcb43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
